Feature/43 person attributes
hitobito/hitobito_cvp pull request #65
Opened 2020-10-22 13:53 UTC by TheWalkingLeek

Are there any model specs needed here? There's no logic inside the model so I figured not but it feels wrong not to add any specs...
refs: #43

2020-10-26 07:48 UTC, psunix approved these changes
:+1:

2020-10-26 07:48 UTC, psunix commented on app/models/cvp/person.rb
> +#  https://github.com/hitobito/hitobito_cvp.
we decided to get rid of those headers :) so only frozen_string_literal: true
also encoding: utf-8 is not required anymore

2020-10-26 07:48 UTC, psunix commented on app/models/cvp/person.rb
> +    Person::PUBLIC_ATTRS << :title << :website << :correspondance_language << :civil_status
Person::PUBLIC_ATTRS.push(:title, :website, ...) ?

2020-10-26 08:25 UTC, amaierhofer reviewed
@TheWalkingLeek Steht nicht explizit im Ticket aber es macht natürlich noch Sinn, wenn diese Felder editiertbar und anzeigbar sind.

2020-10-29 07:54 UTC, amaierhofer commented
@TheWalkingLeek @psunix 

Lizenz Headers sollen drinnen bleiben. Ist sonst nach was in Progress (wegen dem WIP) commit oder ist das jetzt good2go?

2020-10-29 08:24 UTC, TheWalkingLeek commented
Bin noch an den Views, hab die aber bald fertig und ist dann ready. Melde mich wenns soweit ist

2020-10-29 08:58 UTC, TheWalkingLeek commented
Ist jetzt good2go

2020-10-29 10:09 UTC, psunix requested changes
code looks good.
did you copy this with the Salutation pseudo model from somewhere?
I cannot save any of the new attributes like 'title', 'civil_status' ... changes are not persisted.
there's 0 tests ... maybe it makes sense to add at least one test that checks if the custom attributes are there and working probably.

2020-10-29 10:46 UTC, TheWalkingLeek commented
The Salutation implementation is done according to pbs.
The saving #WorksOnMyMachine, I also added the new attributes to the permitted_params inside wagon.rb. Did you reboot the server? @psunix 
I'm gonna look into expanding the specs

2020-10-30 13:08 UTC, merged